import './delegate.forward.test'
import './delegate.reference.test'
import './delegate.vector.test'
import './forward.reference.test'
import './forward.vector.test'
import './reference.vector.test'
import './delegate.reference.vector.test'
