import './delegate/delegate.add.test'
import './delegate/delegate.delete.test'
import './delegate/delegate.has.test'
import './delegate/delegate.symbol.async-iterator.test'
import './delegate/delegate.then.test'
import './delegate/delegate.to-string.test'
